module.exports = {
    prompts: [{
        type: 'checkbox',
        name: 'plugins',
        message: 'Which Cordova plugins would you like to include?',
        choices: [{
            value: 'cordova-plugin-device',
            name: 'cordova-plugin-device',
            checked: true
        },{
            value: 'cordova-plugin-whitelist',
            name: 'cordova-plugin-whitelist',
            checked: true
        },{
            value: 'cordova-plugin-console',
            name: 'cordova-plugin-console',
            checked: true
        }, {
            value: 'ionic-plugin-keyboard',
            name: 'ionic-plugin-keyboard',
            checked: true
        }, {
            value: 'cordova-plugin-splashscreen',
            name: 'cordova-plugin-splashscreen',
            checked: false
        }, {
            value: 'cordova-plugin-statusbar',
            name: 'cordova-plugin-statusbar',
            checked: false
        }, {
            value: 'cordova-plugin-battery-status',
            name: 'cordova-plugin-battery-status',
            checked: false
        }, {
            value: 'cordova-plugin-network-information',
            name: 'cordova-plugin-network-information',
            checked: false
        }, {
            value: 'cordova-plugin-device-motion',
            name: 'cordova-plugin-device-motion',
            checked: false
        }, {
            value: 'cordova-plugin-geolocation',
            name: 'cordova-plugin-geolocation',
            checked: false
        }, {
            value: 'cordova-plugin-device-orientation',
            name: 'cordova-plugin-device-orientation',
            checked: false
        }, {
            value: 'https://github.com/apache/cordova-plugin-camera.git',
            name: 'cordova-plugin-camera',
            checked: false
        }, {
            value: 'cordova-plugin-media-capture',
            name: 'cordova-plugin-media-capture',
            checked: false
        }, {
            value: 'cordova-plugin-media',
            name: 'cordova-plugin-media',
            checked: false
        }, {
            value: 'cordova-plugin-file',
            name: 'cordova-plugin-file',
            checked: false
        }, {
            value: 'cordova-plugin-file-transfer',
            name: 'cordova-plugin-file-transfer',
            checked: false
        }, {
            value: 'cordova-plugin-dialogs',
            name: 'cordova-plugin-dialogs',
            checked: false
        }, {
            value: 'cordova-plugin-vibration',
            name: 'cordova-plugin-vibration',
            checked: false
        }, {
            value: 'cordova-plugin-contacts',
            name: 'cordova-plugin-contacts',
            checked: false
        }, {
            value: 'cordova-plugin-inappbrowser',
            name: 'cordova-plugin-inappbrowser',
            checked: false
        }, {
            value: 'https://github.com/nheezemans/touchid.git',
            name: 'nl.ciber.touchid',
            checked: false
        }, {
            value: 'https://github.com/shazron/KeychainPlugin.git',
            name: 'com.shazron.cordova.plugin.keychainutil',
            checked: false
        }]
    }]
};
